### ISSUE TITLE
Race Condition in pg-read-chars

### ISSUE THREAD

**Issue by swilsons** [emarsden/pg-el#3]
Hi,

I have encountered an intermittent race condition in my use of the library.  Sometimes, when pg-exec is in the main loop reading in DataRow result tuples, it will call pg-read-tuple (which then calls pg-read-chars) while only part of the data for this row has been loaded into the process buffer.  pg-read-chars will then raise an args-out-of-range error as it attempts to read a substring from the process buffer beyond the current end of the buffer.

The simplest workaround I found is to precede the buffer-substring call in pg-read-chars with a call to accept-process-output, using the same logic as in the pg-read-char function.  pg-read-chars becomes:
```elisp
(defun pg-read-chars (connection count)
  (let* ((process (pgcon-process connection))
         (start (pgcon-position connection))
         (end (+ start count)))
    (accept-process-output)
    (prog1 (with-current-buffer (process-buffer process)
             ;; wait for new output, if necessary
             (when (> end (point-max))
               (accept-process-output process 5))
             (buffer-substring start end))
      (setf (pgcon-position connection) end))))
```

-- Sam

**Comment by emarsden** [comment]
Thanks for this fix, I've integrated it in v0.20.
